version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: dugite
    versions:
    - 1.93.0
    - 1.96.0
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: lodash
    versions:
    - 4.17.20
